const HARFORD_CHARACTERS = [
  {
    id: "melian-albor",
    name: "Melian Albor",
    category: "actual",
    type: "Miembro activo",
    role: "Paladín Protección",
    race: "Semielfa noble",
    status: "Activa",
    clearance: "Evaluación operativa",
    accent: "#d4aa4c",
    portrait: "assets/portraits/melian-albor.webp",
    sheet: "assets/dossiers/melian-albor.webp",
    quote: "Solo queríamos escapar de ese infierno, donde estábamos atrapados de forma injusta.",
    summary: "La guardiana. Defensora, mediadora y brújula moral. Cuando la compañía se dispersa entre miedo, deuda o violencia, Melian intenta sostener una línea común.",
    combat: "Defensiva y táctica. Controla el campo, protege a los suyos y prioriza que todos salgan vivos.",
    objective: "Encontrar un futuro donde no tengan que huir ni obedecer por miedo.",
    operations: [],
    notes: "La ficha visual contiene la evaluación completa de fortalezas, debilidades y relaciones internas."
  },
  {
    id: "cody",
    name: "Cody",
    category: "actual",
    type: "Miembro activo",
    role: "Caballero de la Muerte Sangre",
    race: "Humano",
    status: "Activo",
    clearance: "Evaluación operativa",
    accent: "#8fa9ba",
    portrait: "assets/portraits/cody.webp",
    sheet: "assets/dossiers/cody.webp",
    quote: "Ya no queda profesionalidad en la Compañía.",
    summary: "El ejecutor. Tanque de choque, amenaza frontal y catalizador de decisiones. Cuando el grupo se atasca, Cody rompe la inercia con presencia, violencia o una frase seca.",
    combat: "Tanque agresivo. Absorbe daño, mantiene la presión y convierte el miedo en avance.",
    objective: "Recuperar control sobre su destino sin volver a ser simple arma de otros.",
    operations: [],
    notes: "Existe documentación adicional vinculada al IV:7. Su consulta requiere autorización expresa."
  },
  {
    id: "kijava",
    name: "Kijava",
    category: "actual",
    type: "Miembro activo",
    role: "Caballero de la Muerte Escarcha",
    race: "Humano",
    status: "Activo",
    clearance: "Evaluación operativa",
    accent: "#72c9ca",
    portrait: "assets/portraits/kijava.webp",
    sheet: "assets/dossiers/kijava.webp",
    quote: "¿Es que no hemos aprendido nada de la plaga?",
    summary: "El filo silencioso. Presencia de primera línea, acción directa y lealtad sin demasiadas palabras. Cuando el grupo duda, Kijava avanza y convierte la presión en movimiento.",
    combat: "Agresivo y frío. Presiona con doble filo, castiga errores y convierte el avance en amenaza.",
    objective: "Ser algo más que una máquina de matar dentro de una compañía rota.",
    operations: [],
    notes: "El silencio del interesado no debe interpretarse como ausencia de criterio."
  },
  {
    id: "baird",
    name: "Baird",
    category: "actual",
    type: "Miembro activo",
    role: "Druida Feral",
    race: "Huargen",
    status: "Activo",
    clearance: "Evaluación operativa",
    accent: "#aaa65b",
    portrait: "assets/portraits/baird.webp",
    sheet: "assets/dossiers/baird.webp",
    quote: "Así que... una gaviota nos podría ahorrar muchos problemas...",
    summary: "El raro funcional. Explorador, cambiaformas y solucionador improbable. Donde otros ven un disparate, Baird busca una vía natural, social o directamente humillante para evitar que todo acabe a golpes.",
    combat: "Feral y oportunista. Entra, desgasta, busca flancos y convierte el instinto en presión.",
    objective: "Encontrar un lugar donde su rareza sea una virtud, no solo un chiste.",
    operations: [],
    notes: "No descartar sus propuestas antes de comprobar si incluyen animales."
  },
  {
    id: "ziegler-stendel",
    name: "Ziegler Stendel",
    category: "actual",
    type: "Miembro activo",
    role: "Guerrero Protección",
    race: "Humano",
    status: "Activo",
    clearance: "Evaluación operativa",
    accent: "#b8aa6a",
    portrait: "assets/portraits/ziegler-stendel.webp",
    sheet: "assets/dossiers/ziegler-stendel.webp",
    quote: "Empuñad vuestro propio acero, maldita sea.",
    summary: "El muro solemne. Defensor de primera línea, voz de disciplina y choque constante entre honor antiguo y supervivencia moderna. Intenta poner orden en una compañía que vive del caos.",
    combat: "Defensivo y obstinado. Escudo al frente, presión constante y negativa absoluta a retroceder.",
    objective: "Demostrar que aún puede existir honor en una compañía de deudores y fugitivos.",
    operations: [],
    notes: "Las reclamaciones sobre disciplina deberán presentarse directamente al interesado."
  },
  {
    id: "hizdahr-hazdalansen",
    name: "Hizdahr Hazdalansen",
    category: "actual",
    type: "Miembro activo",
    role: "Cazador Puntería",
    race: "Humano",
    status: "Activo",
    clearance: "Evaluación operativa",
    accent: "#c88b2a",
    portrait: "assets/portraits/hizdahr-hazdalansen.webp",
    sheet: "assets/dossiers/hizdahr-hazdalansen.webp",
    quote: "Ojalá tener explosivos.",
    summary: "El tirador imprevisible. Ojo experto, humor seco y soluciones peligrosamente prácticas. Hizdahr convierte la distancia, la duda y el desastre en una oportunidad para disparar primero.",
    combat: "Puntería y distancia. Busca línea de tiro, castiga objetivos clave y convierte la cobertura en ventaja.",
    objective: "Sobrevivir sin dejar de ser él mismo, aunque eso complique cada plan.",
    operations: [],
    notes: "La petición de explosivos continúa pendiente de aprobación."
  },
  {
    id: "bunny",
    name: "Bunny",
    category: "actual",
    type: "Miembro activo",
    role: "Chamán Restauración · Maga",
    race: "Gnoma",
    status: "Activa",
    clearance: "Evaluación operativa",
    accent: "#62c7f0",
    portrait: "assets/portraits/bunny.webp",
    sheet: "assets/dossiers/bunny.webp",
    quote: "Las amistades son como la ingeniería: con mantenimiento, duran más.",
    summary: "La inventora imposible. Sanadora, maga, técnica de campo y corazón raro del grupo. Bunny repara cuerpos, máquinas y ánimos con la misma mezcla de genio, ternura y caos.",
    combat: "Restauración, apoyo y control. Mantiene vivos a los suyos mientras improvisa soluciones mágicas y mecánicas.",
    objective: "Mantener unido al grupo y demostrar que incluso lo roto puede repararse.",
    operations: [],
    notes: "No tocar dispositivos, frascos o piezas marcadas sin consultar primero."
  },
  {
    id: "griker-vaughn",
    name: "Griker Vaughn",
    category: "actual",
    type: "Miembro activo",
    role: "Pícaro Forajido · Ex paladín",
    race: "Huargen",
    status: "Activo",
    clearance: "Evaluación operativa",
    accent: "#b6ad70",
    portrait: "assets/portraits/griker-vaughn.webp",
    sheet: "assets/dossiers/griker-vaughn.webp",
    quote: "La información se la vamos a dar igual. Pero eso no cambia nuestra situación.",
    summary: "El eje cansado. Antiguo paladín, pícaro de recursos y rostro práctico de la compañía. Griker no siempre manda, pero suele ser quien convierte el caos del grupo en una dirección posible.",
    combat: "Forajido móvil y sucio. Aprovecha huecos, presión, engaños y golpes rápidos antes de que el enemigo entienda el plan.",
    objective: "Construir una libertad propia sin volver a ser paladín, preso ni herramienta.",
    operations: [],
    notes: "Parte del expediente permanece censurado por orden interna."
  },
  {
    id: "dornalei",
    name: "Dornalei",
    category: "actual",
    type: "Miembro activo",
    role: "Maga Fuego",
    race: "Elfa de la noche",
    status: "Activa",
    clearance: "Evaluación operativa",
    accent: "#c36bd3",
    portrait: "assets/portraits/dornalei.webp",
    sheet: "assets/dossiers/dornalei.webp",
    quote: "Piromante, para ser específica.",
    summary: "La llama inteligente. Maga de fuego, analista arcana y especialista en convertir conocimiento en ventaja. Dornalei observa primero, calcula después y solo entonces prende fuego al problema.",
    combat: "Fuego y control. Mantiene distancia, castiga errores y convierte el campo de batalla en una ecuación ardiente.",
    objective: "Dominar su poder sin tener que rebajarlo a simple espectáculo o fuerza bruta.",
    operations: [],
    notes: "Los daños por combustión derivados de una discusión académica no están cubiertos por la compañía."
  },
  {
    id: "th-harford",
    name: "T. H. Harford",
    category: "historico",
    type: "Fundador · Archivo histórico",
    role: "Condotiero y fundador",
    race: "Gilneano",
    status: "Histórico",
    clearance: "Archivo fundacional",
    accent: "#4f88b0",
    quote: "El oro compra hombres. Sobrevivir juntos los convierte en compañía.",
    summary: "Fundador de la Compañía Harford y principal responsable de convertir una reunión de mercenarios de baja estofa en una fuerza de fortuna reconocida en los Reinos del Este.",
    biography: [
      "Tras abandonar etapas anteriores de su vida, reunió a soldados de fortuna, veteranos, desertores y criminales de poca monta bajo un estandarte azul. El proyecto nació con una ambición modesta: cobrar contratos y conservar una parte del beneficio.",
      "Bajo su dirección, la compañía participó en las campañas de Lordaeron, la Guerra de las Dos Hordas, la defensa del Portal Oscuro y numerosas operaciones de resultado desigual. Su mando quedó marcado tanto por éxitos notables como por decisiones temerarias y retiradas costosas."
    ],
    personality: "Carismático, tóxico, ambicioso y capaz de mantener unida a gente que difícilmente habría obedecido a cualquier otro.",
    skills: { "Mando": 8, "Combate": 7, "Estrategia": 7, "Diplomacia": 8 },
    operations: ["Fundación de Harford", "Campañas de Lordaeron", "Guerra de las Dos Hordas", "Defensa del Portal Oscuro"],
    notes: "Archivo reconstruido a partir de informes antiguos y testimonios contradictorios."
  },
  {
    id: "aschen-harford",
    name: "Aschen Harford",
    category: "historico",
    type: "Veterano · Archivo histórico",
    role: "Guerrero y sustituto de mando",
    race: "Huargen",
    status: "Histórico",
    clearance: "Expediente veterano",
    accent: "#4f88b0",
    quote: "Una espada no pregunta por qué. El hombre que la empuña debería hacerlo.",
    summary: "Mercenario gilneano que llegó a suplir temporalmente a T. H. Harford durante una convalecencia del fundador. Su gestión fue recordada como accidentada y su trayectoria, como una lucha constante contra sus propios demonios.",
    biography: [
      "Procedente de Piroleña y marcado por la guerra, la pérdida y el cautiverio, terminó viviendo de la espada en diferentes organizaciones antes de incorporarse a la compañía que compartía su apellido.",
      "Asumió el mando durante la ausencia de su primo, sin demasiado éxito. Continuó como mercenario y desapareció durante un periodo prolongado antes de regresar más sereno y mejor preparado."
    ],
    personality: "Obstinado, rígido y propenso a convertir cualquier agravio en una deuda personal.",
    skills: { "Combate": 9, "Montura": 8, "Mando": 5, "Supervivencia": 8 },
    operations: ["Guerra de las Dos Hordas", "Mando provisional", "Campañas de la antigua Harford"],
    notes: "Los testimonios sobre su mando provisional no son especialmente generosos."
  },
  {
    id: "lewyn-landcaster",
    name: "Lewyn Landcaster",
    category: "historico",
    type: "Condotiero · Archivo histórico",
    role: "Propietario e inversor",
    race: "Humano de Arathi",
    status: "Histórico",
    clearance: "Archivo administrativo",
    accent: "#4f88b0",
    quote: "Toda compañía tiene un precio. Mantenerla unida cuesta bastante más.",
    summary: "Noble de Arathi que adquirió e invirtió en la Compañía Harford durante una de sus reconstrucciones, aportando recursos y una nueva dirección política a la organización.",
    biography: [
      "Primogénito de la familia Landcaster, caballero y jinete, terminó relacionado con Harford primero mediante contratos y más tarde como propietario e inversor de la compañía.",
      "Su etapa abrió un nuevo periodo de militarización y operaciones en Kalimdor, coincidiendo con el comienzo de la invasión de la Legión Ardiente."
    ],
    personality: "Ambicioso, orgulloso y más cómodo tratando la guerra como una empresa que como una causa.",
    skills: { "Combate": 8, "Equitación": 9, "Mando": 7, "Finanzas": 8 },
    operations: ["Compra de la compañía", "Operaciones del norte de Kalimdor", "Inicio de la invasión de la Legión"],
    notes: "Consultar los archivos de la familia Landcaster para ampliar la información."
  }
];
