const HARFORD_OPERATIONS = [
  {
    id: "medio-norte-i",
    era: "historico",
    access: "abierto",
    year: "Año 30",
    title: "Primera Campaña de Liberación del Medio Norte",
    subtitle: "Contrato con la Casa Halford",
    location: "Trabalomas · Lordaeron",
    status: "Contrato roto",
    tone: "danger",
    summary: "Primer gran despliegue de la compañía en el norte. La operación terminó cuando las rencillas surgidas durante la toma de un búnker enano hicieron imposible mantener el contrato.",
    objectives: ["Apoyar la reconquista del norte", "Asegurar posiciones próximas a la Muralla de Thoradin", "Sostener la campaña de la Casa Halford"],
    result: "El búnker fue purgado temporalmente, pero el acuerdo se quebró y la posición acabó perdiéndose.",
    participants: ["T. H. Harford", "Casa Halford", "Primeros mercenarios Harford"],
    notes: "Los libros de cuentas no coinciden sobre quién debía pagar las reparaciones del búnker."
  },
  {
    id: "selva-roja",
    era: "historico",
    access: "abierto",
    year: "Año 30",
    title: "Busca y captura: La Selva Roja",
    subtitle: "Caza de Rauss Smirovich",
    location: "Tuercespina",
    status: "Objetivo fugado",
    tone: "danger",
    summary: "Harford recibió el encargo de localizar y entregar a un líder revolucionario. El objetivo escapó, aunque una parte considerable de su red fue destruida durante la persecución.",
    objectives: ["Localizar a Rauss Smirovich", "Desarticular a sus seguidores", "Entregar vivo al objetivo"],
    result: "La red sufrió bajas, pero el objetivo principal no fue capturado.",
    participants: ["Compañía Harford"],
    notes: "Se recomienda no volver a aceptar contratos que incluyan la palabra 'selva' sin adelanto."
  },
  {
    id: "kalimdor-reliquias",
    era: "historico",
    access: "abierto",
    year: "Año 30",
    title: "Expedición a Kalimdor",
    subtitle: "Recuperación de reliquias y artefactos",
    location: "Kalimdor",
    status: "Beneficio alto",
    tone: "success",
    summary: "Una de las pocas expediciones antiguas cuyo resultado contable fue inequívocamente favorable. La compañía regresó al este con reliquias, artefactos y un margen de beneficio digno de recordar.",
    objectives: ["Localizar piezas de valor", "Transportarlas de vuelta a los Reinos del Este", "Evitar reclamaciones de propiedad"],
    result: "Contrato completado con ganancias elevadas.",
    participants: ["Compañía Harford"],
    notes: "La procedencia exacta de varias piezas sigue sin figurar en inventario."
  },
  {
    id: "dos-hordas",
    era: "historico",
    access: "abierto",
    year: "Año 30",
    title: "Guerra de las Dos Hordas",
    subtitle: "Campaña de guerrilla en Los Baldíos",
    location: "Los Baldíos",
    status: "Victoria parcial",
    tone: "success",
    summary: "La campaña más celebrada de la antigua Harford. Sus mercenarios hostigaron convoyes, reunieron suministros y participaron en acciones navales contra las fuerzas garroshistas.",
    objectives: ["Apoyar a las fuerzas aliadas", "Golpear rutas de suministro", "Mantener capacidad de repliegue"],
    result: "Se hundieron naves enemigas y se saquearon convoyes. La retirada se precipitó tras las heridas sufridas por el mando y la negativa de la tropa a avanzar sobre Durotar.",
    participants: ["Compañía Harford", "Alba de Plata", "Casa Halford", "Fuerzas aliadas"],
    notes: "La negativa colectiva a entrar en Durotar consta como decisión táctica, no como motín."
  },
  {
    id: "rutas-del-sur",
    era: "historico",
    access: "abierto",
    year: "Año 30",
    title: "Contrato de las rutas del sur",
    subtitle: "Campaña contra los Corsarios Velasangre",
    location: "Pantano de las Penas · Mar del Sur",
    status: "Punto muerto",
    tone: "danger",
    summary: "La Corona encargó a Harford asegurar las rutas marítimas del sur y del este. La superioridad de los corsarios, la falta de medios y la división interna dejaron la operación a medias.",
    objectives: ["Limpiar las rutas marítimas", "Proteger el comercio de Ventormenta", "Eliminar la presencia corsaria"],
    result: "Fracaso operativo y retirada sin completar el contrato.",
    participants: ["Compañía Harford", "Corsarios Velasangre"],
    notes: "El mar no acepta excusas y los acreedores tampoco."
  },
  {
    id: "muro-de-hierro",
    era: "historico",
    access: "abierto",
    year: "Año 31",
    title: "Operación Muro de Hierro",
    subtitle: "Marcha de Bajaluna a Nagrand",
    location: "Talador · Draenor",
    status: "Derrota severa",
    tone: "danger",
    summary: "El avance hacia Nagrand se deshizo por el desabastecimiento, la caída de la moral y el choque con taumaturgos sombríos orcos. El mando de Harford fue dado por muerto durante un tiempo.",
    objectives: ["Alcanzar Nagrand", "Establecer una punta de lanza", "Apoyar la lucha contra el Imperio Ogro"],
    result: "La compañía quedó desorganizada y obligada a retirarse antes de completar la marcha.",
    participants: ["Compañía Harford", "Fuerzas de la Alianza"],
    notes: "El informe de suministros termina tres días antes que el diario de campaña."
  },
  {
    id: "islas-abruptas",
    era: "historico",
    access: "abierto",
    year: "Año 32",
    title: "Campaña de las Islas Abruptas",
    subtitle: "Fuerte Grajo Negro y Val'sharah",
    location: "Islas Abruptas",
    status: "Contrato completado",
    tone: "success",
    summary: "La compañía combatió junto a aliados de conveniencia en el oeste de las islas y cerró la campaña con el asedio del Fuerte Grajo Negro.",
    objectives: ["Contener el avance demoníaco", "Apoyar las operaciones en Val'sharah", "Participar en el asedio final"],
    result: "Operación registrada como exitosa.",
    participants: ["Compañía Harford", "Vanguardia Illidari", "Alba de Plata"],
    notes: "Uno de los pocos expedientes donde la palabra victoria no necesita matices."
  },
  {
    id: "monte-alto",
    era: "historico",
    access: "abierto",
    year: "Año 32",
    title: "Contrato de Monte Alto",
    subtitle: "Recuperación de mineral",
    location: "Monte Alto",
    status: "Contrato completado",
    tone: "success",
    summary: "Un encargo de los herreros llevó a Harford hasta las montañas para recuperar mineral de calidad. La travesía terminó con éxito pese a los trols oscuros y al estado de la nave.",
    objectives: ["Localizar mineral de calidad", "Asegurar el cargamento", "Regresar por mar"],
    result: "El mineral fue recuperado y La Cucaracha Salada enviada después a reparación.",
    participants: ["Compañía Harford"],
    notes: "El coste de reparar el bergantín redujo considerablemente la sensación de triunfo."
  },
  {
    id: "crimenes-olvidados",
    era: "actual",
    access: "interno",
    year: "Junio-septiembre de 2024 (marcas recuperadas)",
    title: "Crímenes olvidados",
    subtitle: "Traslado frustrado a Tol Barad y supervivencia insular",
    location: "Menethil · Mar de Baradin · Isla sin identificar",
    status: "Expediente inconcluso",
    tone: "warning",
    summary: "El acuerdo con el IV:7 debía terminar con ejecuciones y un traslado a Tol Barad. Un ataque marítimo destruyó el barco y dejó a prisioneros y celadores atrapados en una isla dominada por caníbales, gilgoblins, no-muertos, pigmeos y gaviotas controladas.",
    objectives: ["Cumplir el acuerdo alcanzado en Menethil", "Sobrevivir al naufragio y asegurar suministros", "Encontrar una vía de salida de la isla", "Resolver la amenaza del colgante de Imath"],
    result: "El barco no llegó a Tol Barad. El registro termina después de la destrucción del navío no-muerto, la marcha de Rowan hacia Boralus y la orden de recuperar un colgante destinado a invocar a Imath.",
    participants: ["Griker", "T. H. Harford", "Jen", "Axus", "Niam", "Lindy", "Sasha", "Anthony Parkers", "Rowan O'Coffey"],
    notes: "Las fechas corresponden a anotaciones recuperadas. La equivalencia con el calendario de Azeroth sigue pendiente."
  },
  {
    id: "refectorio-silencio",
    era: "actual",
    access: "interno",
    year: "Registro reciente",
    title: "Refectorio del Silencio",
    subtitle: "Incidente vinculado a Karazhan",
    location: "Karazhan",
    status: "Cerrado con reservas",
    tone: "warning",
    summary: "Una operación posterior a Tol Barad condujo al grupo hasta un enclave de Karazhan marcado por el silencio, la magia y documentos cuya circulación sigue limitada.",
    objectives: ["Investigar el enclave", "Recuperar información", "Salir con el mayor número posible de miembros"],
    result: "Objetivos principales cubiertos. Consecuencias pendientes de archivo.",
    participants: ["Compañía Harford"],
    notes: "No reproducir sonidos registrados en el interior del refectorio."
  },
  {
    id: "llegada-chapaleos",
    era: "actual",
    access: "abierto",
    year: "Etapa actual",
    title: "Llegada a Chapaleos",
    subtitle: "Instalación de fortuna",
    location: "Chapaleos",
    status: "Base establecida",
    tone: "success",
    summary: "Harford llegó a la isla sin dinero después de atravesar el Pantano. La falta de recursos convirtió cualquier encargo razonablemente pagado en una prioridad inmediata.",
    objectives: ["Encontrar alojamiento", "Conseguir ingresos", "Reconstruir una red de contactos"],
    result: "La compañía logró instalarse y comenzar a aceptar trabajos locales.",
    participants: ["Compañía Harford"],
    notes: "La palabra 'establecida' se usa aquí con generosidad administrativa."
  },
  {
    id: "brote-slimes",
    era: "actual",
    access: "abierto",
    year: "Etapa actual",
    title: "Brote de slimes",
    subtitle: "Primeros trabajos en la isla",
    location: "Chapaleos",
    status: "Incidente contenido",
    tone: "success",
    summary: "Una proliferación de criaturas viscosas puso a prueba a la compañía poco después de su llegada y sirvió como primera demostración pública de utilidad.",
    objectives: ["Contener el brote", "Reducir daños", "Cobrar el trabajo"],
    result: "Amenaza contenida y reputación local ligeramente mejorada.",
    participants: ["Compañía Harford"],
    notes: "Las reclamaciones por ropa disuelta fueron rechazadas."
  },
  {
    id: "plataforma-petronegro",
    era: "actual",
    access: "interno",
    year: "Etapa actual",
    title: "Plataforma Petronegro",
    subtitle: "Encargo industrial y extracción",
    location: "Aguas de Chapaleos",
    status: "Expediente restringido",
    tone: "warning",
    summary: "Industrias Petronegro contrató a Harford para intervenir en una plataforma petrolífera. El informe mezcla riesgos industriales, presencia hostil y decisiones tomadas sin apoyo suficiente.",
    objectives: ["Acceder a la plataforma", "Resolver el incidente", "Extraer al personal de Harford"],
    result: "Operación completada. Detalles bloqueados por cláusula contractual.",
    participants: ["Compañía Harford", "Industrias Petronegro"],
    notes: "Todo documento con sello Petronegro debe copiarse antes de devolverlo."
  },
  {
    id: "asalto-cobras",
    era: "actual",
    access: "interno",
    year: "Etapa actual",
    title: "Asalto de los Cobras",
    subtitle: "Incidente en la base militar",
    location: "Chapaleos",
    status: "Respuesta de emergencia",
    tone: "danger",
    summary: "La organización conocida como los Cobras atacó una instalación militar, obligando a Harford a responder en un escenario con objetivos poco claros y demasiados actores armados.",
    objectives: ["Sobrevivir al asalto", "Evitar la pérdida total de la instalación", "Identificar a los responsables"],
    result: "Ataque contenido. La red de los Cobras siguió activa.",
    participants: ["Compañía Harford", "Cobras", "Personal militar local"],
    notes: "La copia abierta omite quién abrió primero la puerta equivocada."
  },
  {
    id: "operacion-100-delicias",
    era: "actual",
    access: "interno",
    year: "Etapa actual",
    title: "Operación 100 Delicias",
    subtitle: "Intervención contra una red criminal",
    location: "Chapaleos",
    status: "Objetivos parciales",
    tone: "warning",
    summary: "Una cadena de encargos relacionada con Fisto, Hell Here y Penasombría llevó a Harford a intervenir en una red criminal más amplia de lo previsto.",
    objectives: ["Reunir información", "Golpear la infraestructura criminal", "Evitar comprometer la cobertura"],
    result: "Varios objetivos fueron cubiertos, aunque la red no quedó completamente desmantelada.",
    participants: ["Compañía Harford", "Contactos locales", "Actores clasificados"],
    notes: "El nombre de la operación no fue elegido por el archivero."
  },
  {
    id: "almacen-pantano",
    era: "actual",
    access: "clasificado",
    year: "Etapa actual",
    title: "Segundo almacén del pantano",
    subtitle: "Enlace con frecuencia segura",
    location: "Pantano de Chapaleos",
    status: "Clasificado",
    tone: "danger",
    summary: "La compañía recibió instrucciones para localizar y destruir un segundo centro de almacenamiento vinculado a la red de droga de la isla. La documentación pública concluye antes del contacto con el objetivo Kelki.",
    objectives: ["Localizar el almacén", "Destruir existencias", "Neutralizar al responsable"],
    result: "Información visible limitada por acuerdo con el enlace externo.",
    participants: ["Compañía Harford", "Dardo", "Enlace externo"],
    notes: "Acceso condicionado a autorización de la frecuencia segura."
  },
  {
    id: "laboratorio-teleportacion",
    era: "actual",
    access: "interno",
    year: "Etapa actual",
    title: "Laboratorio de teleportación",
    subtitle: "Incidente arcano y logístico",
    location: "Chapaleos",
    status: "Archivo abierto",
    tone: "warning",
    summary: "Una instalación dedicada a la teleportación apareció vinculada a la red de operaciones de la isla. La recuperación de pruebas y el control del lugar generaron nuevos riesgos.",
    objectives: ["Asegurar el laboratorio", "Recuperar documentación", "Evitar una fuga arcana"],
    result: "Expediente aún en revisión.",
    participants: ["Compañía Harford"],
    notes: "No activar círculos, palancas ni cristales durante la catalogación."
  }
];
